- name: Download calico manifest
  shell: |
    wget --limit-rate 1k https://docs.projectcalico.org/manifests/calico.yaml -P /tmp
    chmod 0755 /tmp/calico.yaml
  args:
    warn: false

- name: Set veth_mtu
  replace:
    path: /tmp/calico.yaml
    regexp: 'veth_mtu\:.*'
    replace: 'veth_mtu: "{{ calico_mtu }}"'

- name: kubectl
  command: kubectl create -f /tmp/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
